version: '3'
services:
  nginx:
      image: nginx:alpine
      ports: 
         - "9090:80"
      networks:
         - internal
      volumes: 
         -  C:\Users\Benson\Desktop\code\glpi:/usr/share/nginx/html/
         -  C:\Users\Benson\Desktop\code\glpi:/var/www/html/
         -  C:\Users\Benson\Desktop\code\glpi/default.conf:/etc/nginx/conf.d/default.conf
         - ./logs/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes: 
         -   C:\Users\Benson\Desktop\code\glpi:/var/www/html/
         -  ./logs/php.log:/var/log/fpm-php.www.log

networks:
  internal:
    driver: bridge